# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: Copyright contributors to the vLLM project
"""Diffusion integration surface for the pluggable Host Weight Runtime."""

# Keep legacy direct-import attributes available while ``__all__`` defines the
# smaller, supported star-import surface.
# ruff: noqa: F401

from .binding import (
    BindingController,
    BindingError,
    BindingValidationError,
    DiffusionConsumerBinder,
    PreparedBindingCommitState,
    PreparedModuleBinding,
)
from .build_coordination import (
    BuildComposition,
    BuildCoordinationError,
    BuilderCoordinator,
    FileBuilderCoordinator,
    compose_first_c4_build,
    launch_id_for_first_c4,
)
from .catalog import (
    ArtifactUnit,
    ArtifactUnitDeclaration,
    CatalogError,
    ModuleScope,
    TensorRole,
    TensorTarget,
    TransferUnit,
    TransferUnitDeclaration,
    WeightCatalog,
    build_weight_catalog,
)
from .evidence import (
    HWR_RESOLUTION_EVIDENCE_SCHEMA_VERSION,
    HostWeightResolutionEvidence,
    evidence_from_outcome,
    not_requested_evidence,
    preparation_failure_evidence,
)
from .formats import (
    FORMAT_BINDING_RECIPE_SCHEMA_VERSION,
    ArtifactFormatExporter,
    BindingDestination,
    ConsumerFormatAdapter,
    FinalizedTensor,
    FinalizedTensorSet,
    FormatBindingRecipe,
    FormatContractError,
    FormatTensorRole,
    Fp8FormatError,
    Fp8PerTensorFormatAdapter,
    LayerFormatSpec,
    LayerTensorBinding,
    ModuleStateKind,
    OptionalLayerTensorBinding,
    RequiredLayerTensorBinding,
    TargetModulePath,
    WeightFormatAdapter,
)
from .model_integration import (
    HOST_WEIGHT_MODEL_INTEGRATION_ABI,
    ConsumerSkeletonFactory,
    DiffusionPipelineSpec,
    HostWeightModelIntegrationBundle,
    ModelIntegrationCapabilities,
    ModelIntegrationError,
    ModelIntegrationLegacyClassification,
    ModelIntegrationRegistry,
    ModelIntegrationSelectionError,
    ModelIntegrationSupportDecision,
    ModelIntegrationUnavailableError,
    ModelWeightSource,
    PreparedModelIntegration,
    ProducerFactoryContext,
    SkeletonFactoryContext,
)
from .ownership import (
    FatalPreparationFailure,
    LegacyReason,
    PreparationCleanupHandle,
    PreparedSessionReady,
    RetryablePreparationFailure,
    UseLegacy,
    WeightAccessSessionFactoryResult,
    WeightConsumer,
    WeightConsumerOwner,
    WeightConsumerOwnerPhase,
)
from .session import (
    BindingStateError,
    DetachMode,
    DeviceBinding,
    DeviceBindingLifetime,
    HostCopyMode,
    PreparedWeightAccessSession,
    PreparedWeightUnit,
    ReleaseTarget,
    SessionBusy,
    SessionCapabilities,
    SessionClosed,
    SessionError,
    SessionRequirements,
    UnitOutsideSelectedPlan,
    UnitReadRequest,
    WeightAccessSession,
)
from .skeleton import (
    ConsumerCandidateOrigin,
    ConsumerPipelineCandidate,
    PipelineSkeleton,
    SkeletonError,
)
from .topology import (
    ArtifactTopology,
    ParallelRanks,
    RuntimeTopology,
    TopologyError,
    TopologySupportDecision,
    TransferMode,
    TransferTopology,
    adapt_diffusion_parallel_config,
    evaluate_single_node_complete_v1,
)
from .transfer import (
    DtypePlaneSpec,
    ModuleUnitBinding,
    PlaneId,
    TensorBindingSpec,
    TensorPlacement,
    TransferCatalog,
    TransferPlan,
    TransferPlanError,
    TransferPlanKind,
    TransferUnitSpec,
    UnitKind,
    allocate_host_planes,
    compute_exact_coverage_digest,
    compute_transfer_catalog_digest,
    tensor_views_for_unit,
    validate_plane_buffers,
)

__all__ = [
    "ArtifactFormatExporter",
    "BindingStateError",
    "ConsumerCandidateOrigin",
    "ConsumerFormatAdapter",
    "ConsumerPipelineCandidate",
    "ConsumerSkeletonFactory",
    "DetachMode",
    "DeviceBinding",
    "DeviceBindingLifetime",
    "DiffusionPipelineSpec",
    "FatalPreparationFailure",
    "FinalizedTensor",
    "FinalizedTensorSet",
    "FormatBindingRecipe",
    "FormatContractError",
    "HOST_WEIGHT_MODEL_INTEGRATION_ABI",
    "HostCopyMode",
    "HostWeightResolutionEvidence",
    "HostWeightModelIntegrationBundle",
    "LayerFormatSpec",
    "LayerTensorBinding",
    "LegacyReason",
    "ModelIntegrationCapabilities",
    "ModelIntegrationError",
    "ModelIntegrationLegacyClassification",
    "ModelIntegrationRegistry",
    "ModelIntegrationSelectionError",
    "ModelIntegrationSupportDecision",
    "ModelIntegrationUnavailableError",
    "ModelWeightSource",
    "PipelineSkeleton",
    "PreparationCleanupHandle",
    "PreparedModelIntegration",
    "PreparedSessionReady",
    "PreparedWeightAccessSession",
    "PreparedWeightUnit",
    "ProducerFactoryContext",
    "RetryablePreparationFailure",
    "ReleaseTarget",
    "SessionBusy",
    "SessionCapabilities",
    "SessionClosed",
    "SessionError",
    "SessionRequirements",
    "SkeletonFactoryContext",
    "SkeletonError",
    "TransferCatalog",
    "TransferPlan",
    "TransferPlanKind",
    "TransferPlanError",
    "TransferUnitSpec",
    "UnitKind",
    "UnitReadRequest",
    "UnitOutsideSelectedPlan",
    "UseLegacy",
    "WeightAccessSession",
    "WeightAccessSessionFactoryResult",
    "WeightCatalog",
    "WeightConsumer",
    "WeightConsumerOwner",
    "WeightConsumerOwnerPhase",
    "WeightFormatAdapter",
]
