# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: Copyright contributors to the vLLM project
"""Independent single-node Host Weight Runtime public API."""

# Keep legacy direct-import attributes available while ``__all__`` defines the
# smaller, supported star-import surface.
# ruff: noqa: F401

from .artifact import ResolvedArtifact, WeightView
from .backings import (
    BackingClosedError,
    BackingError,
    BackingIntegrityError,
    BackingProvider,
    BackingProviderRegistry,
    EphemeralBackingProvider,
    LoadedTensorBacking,
    LoadedTensorBackingProvider,
    RuntimeMmapBacking,
    StaticBackingProviderRegistry,
    WeightBacking,
    tensor_spec_from_tensor,
    torch_dtype_name,
)
from .composition import (
    create_default_backing_provider_registry,
    create_default_host_weight_runtime,
)
from .contracts import (
    SCHEMA_VERSION,
    AccessFeature,
    AccessRequirements,
    ArtifactAlreadyReady,
    ArtifactBuildSession,
    ArtifactManifest,
    ArtifactProducer,
    ArtifactRecord,
    ArtifactSink,
    ArtifactSpec,
    ArtifactTopologyDescriptor,
    BackingCapabilities,
    BackingIndex,
    BackingKind,
    BuildAuthorization,
    BuilderInitialSignalState,
    BuilderStarted,
    BuilderStartFailed,
    BuilderStartGate,
    BuilderStartPublisher,
    BuilderStartTimeout,
    BuildFailureClassification,
    BuildFailureKind,
    BuildFailureStage,
    BuildGateOutcome,
    BuildIntent,
    BuildRole,
    BuildSessionCleanupRegistry,
    CapabilitiesUnavailable,
    CapabilityDecision,
    CapabilityGrant,
    ContractError,
    HostCopyMode,
    JSONScalar,
    JSONValue,
    ProducerDescriptor,
    ResolvedArtifactRegistrar,
    StorageObject,
    StorageSpan,
    TensorRole,
    TensorSelection,
    TensorSpec,
    TopologyCoordinate,
    WeightFormatDescriptor,
    canonical_digest,
    canonical_json,
    derive_weight_format_plan_digest,
    dtype_item_size,
    required_storage_numel,
)
from .identity import derive_artifact_key, derive_manifest_compatibility_digest
from .outcomes import (
    FatalFailure,
    Ready,
    ResolutionInfo,
    ResolutionPath,
    ResolvedAccess,
    ResolveOutcome,
    RetryableFailure,
)
from .runtime import HostWeightRuntime, RuntimeBusy, RuntimeCapabilities, RuntimeClosed
from .store import (
    ArtifactRepository,
    Builder,
    BuilderFailed,
    BuildLease,
    Existing,
    LocalArtifactRepository,
    LocalRuntimeMmapBackingProvider,
    NoBuilder,
    ReservationError,
    RuntimeMmapArtifactSink,
    StoreCorruptionError,
    StoreError,
    StorePublicationDurabilityError,
    Waiter,
    WaitTimeout,
)
from .validation import validate_manifest_against_spec

__all__ = [
    "AccessFeature",
    "AccessRequirements",
    "ArtifactBuildSession",
    "ArtifactManifest",
    "ArtifactProducer",
    "ArtifactRepository",
    "ArtifactSink",
    "ArtifactSpec",
    "ArtifactTopologyDescriptor",
    "BackingCapabilities",
    "BackingIndex",
    "BackingKind",
    "BackingProvider",
    "BackingProviderRegistry",
    "BuildAuthorization",
    "BuildIntent",
    "BuildSessionCleanupRegistry",
    "BuilderStartGate",
    "BuilderStartPublisher",
    "CapabilitiesUnavailable",
    "CapabilityDecision",
    "CapabilityGrant",
    "ContractError",
    "FatalFailure",
    "HostWeightRuntime",
    "LocalArtifactRepository",
    "ProducerDescriptor",
    "Ready",
    "ResolveOutcome",
    "ResolvedArtifact",
    "ResolvedArtifactRegistrar",
    "ResolvedAccess",
    "ResolutionInfo",
    "ResolutionPath",
    "RetryableFailure",
    "RuntimeBusy",
    "RuntimeCapabilities",
    "RuntimeClosed",
    "StorageObject",
    "StorageSpan",
    "TensorSelection",
    "TensorSpec",
    "TopologyCoordinate",
    "WeightBacking",
    "WeightFormatDescriptor",
    "WeightView",
    "canonical_digest",
    "create_default_backing_provider_registry",
    "create_default_host_weight_runtime",
    "derive_artifact_key",
    "derive_manifest_compatibility_digest",
    "derive_weight_format_plan_digest",
    "validate_manifest_against_spec",
]
